version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smart-documents-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-multiple-databases.sql:/docker-entrypoint-initdb.d/init-multiple-databases.sql
    networks:
      - smart-documents-network

  book-inventory-service:
    container_name: book-inventory-service
    image: gradle:7.6.1-jdk17
    working_dir: /book-app
    volumes:
      - ./BookInventoryService:/book-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/books?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: book_user
      SPRING_DATASOURCE_PASSWORD: book_password
    networks:
      - smart-documents-network
    command: gradle bootRun

  order-management-service:
    container_name: order-management-service
    image: gradle:7.6.1-jdk17
    working_dir: /order-app
    volumes:
      - ./OrderManagementService:/order-app
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orders?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_password
    networks:
      - smart-documents-network
    command: gradle bootRun

networks:
  smart-documents-network:
    driver: bridge

volumes:
  mysql_data:
